version: '3'

services:
  database:
    image: 'postgres:latest'
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - /var/run/postgresql:/var/run/postgresql
        #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./src/
    network_mode: "host"
