name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install poetry
    - run: poetry install
    - run: poetry run pytest
    - run: poetry build
  docker-build:
    runs-on: ubuntu-latest
    name: Build Docker image 
    steps:
      - 
      uses: docker/build-push-action@v4.0.0
      with:
        file: ./src/Dockerfile
        push: false
        tags: pedroallenrevez/unbabel:latest


